### ISSUE TITLE
undefined reference to `vtable`

### ISSUE THREAD

**Issue by ZanzyTHEbar** [paclema/MQTTClient#10]
Hello, 

Great library!

i have followed the the example `basic_class_with_mqtt`

Here is my [code](https://github.com/ZanzyTHEbar/ESP32GreenhouseTowerDIY/tree/main/Code/PlatformIO%20Project/lib/GreenHouseTowerDIY/src/local/network/mqtt/basic)

I am getting the error:
```cpp
.pio/build/esp32dev_hardware_debug/libd8b/libGreenHouseTowerDIY.a(basicmqtt.cpp.o):(.literal._ZN8BaseMQTTC2ER16GreenHouseConfigR13ProjectConfigP10MQTTClient+0x4): undefined reference to `vtable for BaseMQTT'
```
Which is confusing me tbh, as to my knowledge i am properly constructing my class (just the standard way for cpp tbh) and overriding the `MQTTClientCallback` interface methods.

Not exactly sure what's going on here. Note - the issue is definitely with this library, project compiles fine when i don't use it.

**Comment by ZanzyTHEbar** [comment]
I fixed the issue: 

I converted the `MQTTClientCallback` into a pure virtual interface and then implemented the methods and properly override them.

Then, I had to remove the ArduinoJson objects from the initializer list and locally scoped it (duh, should've done that to begin with).

Finally, I passed the `MQTTClient` by reference, instead of creating an owned pointer.

**Comment by ZanzyTHEbar** [comment]
Just an update - I am loving this library. Performant, no deps, uses espressif API's, an on my esp32 is aync. Great lib mate :).

**Comment by paclema** [comment]
Hello @ZanzyTHEbar I am happy to hear that it worked and that it helped you! Thank you also for your comments :) Your project looks awesome too!
